# Generated by Django 5.0.1 on 2024-02-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='point',
            field=models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'not bad'), ('4', 'good'), ('5', 'very good')], default='1', max_length=10),
        ),
    ]
