# Generated by Django 5.0.1 on 2024-02-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_daler',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
