# Generated by Django 5.0.1 on 2024-02-21 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
